name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build-prod
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  
